### ISSUE TITLE
Test vectors organization 

### ISSUE THREAD

**Issue by ttjsu-aws** [awslabs/aws-encryption-sdk-test-vectors#7]
I was wondering if we want to make changes in the way the test vectors are organized to make it easier to identity and search for it. 

Currently the directory looks like this: 
```
── vectors/
│   │   ├── full-message-decrypt/
│   │   │   └── python-1.3.5.zip
│   │   ├── python-1.3.0.zip
```

Maybe we could move to something like this? 
```
── vectors/
│   │   ├── full-message-encrypt/
│   │   │   └── python-1.3.5.zip
│   │   ├── full-message-decrypt/
│   │   │   └── python-1.3.5.zip
│   │   ├── legacy/
│   │   │   └── python-1.3.0.zip
```

**Comment by ttjsu-aws** [comment]
In the spirit of organization, For the contents of each test-vector zip file- do we have a format we want to follow? Maybe something along these lines? 
```
── IMPLEMENTATION-VERSION.zip/
│   │   ├── plaintexts/
│   │   │   └── <text size name>
│   │   ├── ciphertexts/
│   │   │   └── <test case uuid>
│   │   ├── manifests/
│   │   │   └── <manifest-name>
```

For Example: 
Currently, the contents of `python-1.3.5.zip` will be 

```
── python-1.3.5.zip/
│   │   ├── plaintexts/
│   │   │   └── <text size name>
│   │   ├── ciphertexts/
│   │   │   └── <test case uuid>
│   │   ├──  manifests/
│   │   │   └── decrypt_message.json
│   │   │   └── keys.json
```

**Comment by mattsb42-aws** [comment]
Agreed on the repo organization. For the zip organization, really the only thing that we care about is the entry-point manifest. For that, I think it would be reasonable to just state that the entry-point manifest must be called `manifest.json`.

**Comment by ttjsu-aws** [comment]
Alright, the entry point being called `manifest.json` sounds good to me. We would still have a `keys.json` file with the keys thought right?

**Comment by mattsb42-aws** [comment]
The rest of the files are irrelevant. The entry-point manifest defines the rest of the contents of the zip.

**Comment by david-koenig** [comment]
It's not clear to me why we're using zip files at all. That just makes it harder to browse and maintain the files.

**Comment by david-koenig** [comment]
@mattsb42-aws Thanks, this is a helpful explanation. I'm curious about the process used to generate the files and whether the files fit into distinct categories in terms of the features being tested. But this isn't urgent, if you'd prefer to explain this in person when you're back in the office rather than writing out a lot of detail here.

**Comment by dougch** [comment]
Re-closing.
